dist: trusty
language: go
go_import_path: github.com/thedarnproject/thedarnapi
matrix:
  include:
  - go: 1.7
  - go: 1.8
install:
- true
before_deploy:
- "./scripts/generate-bintray-json.sh"
deploy:
  provider: bintray
  repo: thedarnproject/thedarnapi
  file: "./.bintray.json"
  user: "${BINTRAY_USER}"
  key: "${BINTRAY_KEY}"
  skip_cleanup: true
  on:
    branch: "**"
    go: 1.8
